version: "3.3"
services:
  db:
    # image: arm64v8/postgres # Uncomment for Mac M-series processors
    image: postgres # Uncomment for windows
    restart: always
    hostname: localhost
    environment:
      POSTGRES_DB: "inventory_manager"
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "5432:5432"
    expose:
      # Opens port 3306 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - ./volume:/var/lib/postgresql
